; chunkboot.s — chunked-boot loader for spare-CPU program slots.
; GENERATED by gen_chunkboot.py.
;
; A self-contained .orx baked into spare CPUs at launcher startup.
; See examples/linkboot/gen_chunkboot.py for the wire protocol, the
; OR-slot allocation, and how the loader hands off to the guest via
; simorisc's InstallProgram primitive (call #0x009).

.entry main

.set TAG_CODE,    0x4100
.set TAG_DATA,    0x4102
.set CHUNK_BYTES, 256

.text

main:
    ; Save PROCID (R7) so we can include it in announce/ack SENDs.
    addu  r16, r7, r0

    ; Save R6 — simorisc's reset_cpu primes it with the *previous*
    ; guest's TaskExit code so we can include it in our first
    ; "ready" announce. Linkbootd uses that to surface the real
    ; exit code to the shell instead of always reporting 0. On the
    ; very first boot R6 is just the default 0 (no prior run).
    addu  r27, r6, r0                  ; r27 = previous exit code

    ; Save the V-cap-bearing self-svc into O15 — every queue poll
    ; overwrites O1..O4 with the sender's OR payload, so we'd lose
    ; the full ref otherwise.
    omov  o15, o4

    ; Derive an R+S self-ref into O6. The boot O6 is a "pad" service
    ; slot that we don't pass through to the guest, so it's free to
    ; hijack. The R+S ref is what the master needs to SEND chunks
    ; back to us.
    omov  o1, o4
    addiu r4, r0, 0x09                 ; R|S
    call  #0x103                       ; ObjDerive
    bne   r2, r0, fail
    nop
    omov  o6, o1                       ; o6 = R+S self-ref

    ; Attach a receive queue to the self-service.
    omov  o1, o15
    addiu r4, r0, 4
    call  #0x203                       ; ReceiveQueueAttach
    bne   r2, r0, fail
    nop

    ; r17 = next_offset across iterations. Starts at 0 (initial
    ; announce). r18 also starts at 0; cleared once we've Object-
    ; Alloc'd the text/data dst objects.
    addu  r17, r0, r0                  ; next_offset
    addu  r18, r0, r0                  ; alloc_done flag (0 = not yet)

; ---------------------------------------------------------------------------
; Request loop. Sends one announce/ack SEND, blocks for one chunk,
; copies it into the dst object, and either continues or finalizes.
; ---------------------------------------------------------------------------

req_loop:
    ; Announce/ack SEND.
    omov  o1, o5                       ; recipient = linkbootd
    omov  o2, o6                       ; R+S self-ref
    onull o3
    onull o4
    addu  r4, r16, r0                  ; PROCID
    addu  r5, r17, r0                  ; next_offset
    addu  r6, r27, r0                  ; previous exit code (initial
                                       ; announce only — meaningful
                                       ; when next_offset == 0)
    addiu r7, r0, 0
    send  o1

    ; Wait for chunk.
    omov  o1, o15
    addiu r4, r0, -1                   ; infinite
    call  #0x204                       ; ReceiveQueuePoll
    bne   r2, r0, fail
    nop

    ; Queue dispatch: O2 = chunk source; R3 = chunk_position;
    ; R4 = chunk_byte_length; R5 = total_text; R6 = total_data.
    addu  r19, r3, r0                  ; chunk_position
    addu  r20, r4, r0                  ; chunk_byte_length
    addu  r21, r5, r0                  ; total_text_size
    addu  r22, r6, r0                  ; total_data_size
    omov  o12, o2                      ; chunk source ref

    ; First chunk? r18 != 0 means we already allocated.
    bne   r18, r0, copy_chunk
    nop

    ; ObjAlloc text (size = r21).
    addu  r4, r21, r0
    addiu r5, r0, TAG_CODE
    addiu r6, r0, 0x47                 ; R|W|X|C
    addiu r7, r0, 0
    call  #0x100                       ; ObjAlloc
    bne   r2, r0, fail
    nop
    omov  o13, o1                      ; o13 = writable text obj

    ; MapObject text as R|W → text_va in r3.
    omov  o1, o13
    addiu r4, r0, 0
    addiu r5, r0, 0
    addiu r6, r0, 0x03                 ; R|W
    addu  r7, r21, r0
    call  #0x110
    bne   r2, r0, fail
    nop
    addu  r23, r3, r0                  ; r23 = text_va

    ; If data_size > 0, ObjAlloc data + map R|W.
    beq   r22, r0, alloc_done
    nop
    addu  r4, r22, r0
    addiu r5, r0, TAG_DATA
    addiu r6, r0, 0x43                 ; R|W|C  (no X)
    addiu r7, r0, 0
    call  #0x100                       ; ObjAlloc
    bne   r2, r0, fail
    nop
    omov  o14, o1                      ; o14 = writable data obj

    omov  o1, o14
    addiu r4, r0, 0
    addiu r5, r0, 0
    addiu r6, r0, 0x03                 ; R|W
    addu  r7, r22, r0
    call  #0x110
    bne   r2, r0, fail
    nop
    addu  r24, r3, r0                  ; r24 = data_va

alloc_done:
    addiu r18, r0, 1                   ; mark allocations done

copy_chunk:
    ; Decide dst: chunk_position < text_size → text, else data.
    ; r25 = write base; r19 + r20 used to compute next_offset later.
    sltu  r1, r19, r21                 ; r1 = (chunk_position < text_size)
    bne   r1, r0, copy_to_text
    nop
    ; Data chunk: write base = data_va + (chunk_position - text_size)
    subu  r25, r19, r21
    addu  r25, r25, r24
    j     copy_words
    nop
copy_to_text:
    ; Text chunk: write base = text_va + chunk_position
    addu  r25, r23, r19

copy_words:
    ; Words to copy = chunk_byte_length / 4.
    srl   r26, r20, 2

    ; Unrolled OLW + SW with early-exit on r1 == r26. One stanza per
    ; word in the 256-byte chunk window. Each OLW immediate
    ; is encoded into the instruction so each stanza is hardcoded.
    addu  r1, r0, r0
    olw   r2, 0(o12)
    sw    r2, 0(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 4(o12)
    sw    r2, 4(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 8(o12)
    sw    r2, 8(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 12(o12)
    sw    r2, 12(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 16(o12)
    sw    r2, 16(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 20(o12)
    sw    r2, 20(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 24(o12)
    sw    r2, 24(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 28(o12)
    sw    r2, 28(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 32(o12)
    sw    r2, 32(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 36(o12)
    sw    r2, 36(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 40(o12)
    sw    r2, 40(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 44(o12)
    sw    r2, 44(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 48(o12)
    sw    r2, 48(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 52(o12)
    sw    r2, 52(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 56(o12)
    sw    r2, 56(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 60(o12)
    sw    r2, 60(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 64(o12)
    sw    r2, 64(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 68(o12)
    sw    r2, 68(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 72(o12)
    sw    r2, 72(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 76(o12)
    sw    r2, 76(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 80(o12)
    sw    r2, 80(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 84(o12)
    sw    r2, 84(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 88(o12)
    sw    r2, 88(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 92(o12)
    sw    r2, 92(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 96(o12)
    sw    r2, 96(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 100(o12)
    sw    r2, 100(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 104(o12)
    sw    r2, 104(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 108(o12)
    sw    r2, 108(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 112(o12)
    sw    r2, 112(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 116(o12)
    sw    r2, 116(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 120(o12)
    sw    r2, 120(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 124(o12)
    sw    r2, 124(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 128(o12)
    sw    r2, 128(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 132(o12)
    sw    r2, 132(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 136(o12)
    sw    r2, 136(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 140(o12)
    sw    r2, 140(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 144(o12)
    sw    r2, 144(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 148(o12)
    sw    r2, 148(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 152(o12)
    sw    r2, 152(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 156(o12)
    sw    r2, 156(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 160(o12)
    sw    r2, 160(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 164(o12)
    sw    r2, 164(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 168(o12)
    sw    r2, 168(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 172(o12)
    sw    r2, 172(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 176(o12)
    sw    r2, 176(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 180(o12)
    sw    r2, 180(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 184(o12)
    sw    r2, 184(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 188(o12)
    sw    r2, 188(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 192(o12)
    sw    r2, 192(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 196(o12)
    sw    r2, 196(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 200(o12)
    sw    r2, 200(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 204(o12)
    sw    r2, 204(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 208(o12)
    sw    r2, 208(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 212(o12)
    sw    r2, 212(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 216(o12)
    sw    r2, 216(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 220(o12)
    sw    r2, 220(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 224(o12)
    sw    r2, 224(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 228(o12)
    sw    r2, 228(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 232(o12)
    sw    r2, 232(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 236(o12)
    sw    r2, 236(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 240(o12)
    sw    r2, 240(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 244(o12)
    sw    r2, 244(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 248(o12)
    sw    r2, 248(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
    olw   r2, 252(o12)
    sw    r2, 252(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
chunk_done:
    ; next_offset = chunk_position + chunk_byte_length.
    addu  r17, r19, r20

    ; Total = text + data. Last chunk if next_offset == total.
    addu  r1, r21, r22
    beq   r17, r1, finalize
    nop
    j     req_loop
    nop

finalize:
    ; ObjDerive text → R|X|C (drop W).
    omov  o1, o13
    addiu r4, r0, 0x45                 ; R|X|C
    call  #0x103                       ; ObjDerive
    bne   r2, r0, fail
    nop
    omov  o13, o1

    ; If data exists, ObjDerive data → R|C (drop W from the ref
    ; itself). Match init_cpu's contract: the data REF is R|C, but
    ; InstallProgram's R|W mapping makes VA-based stores to globals
    ; work just like for a freshly-init'd program. OCAP sees R|C.
    beq   r22, r0, install
    nop
    omov  o1, o14
    addiu r4, r0, 0x41                 ; R|C
    call  #0x103
    bne   r2, r0, fail
    nop
    omov  o14, o1

install:
    ; Shift the boot service ORs down so the guest sees the standard
    ; ABI (O5 = console, O6 = keyboard, O10 = hostfsd).
    omov  o5, o7
    omov  o6, o8
    onull o7
    onull o8
    onull o9
    omov  o10, o11

    ; CALL InstallProgram. Args: O1 = code ref, O3 = data ref (or
    ; null), R4 = entry offset (always 0 for pcc-built programs).
    omov  o1, o13                      ; guest text ref (R|X|C)
    beq   r22, r0, install_no_data
    nop
    omov  o3, o14                      ; guest data ref (R|C)
    j     install_call
    nop
install_no_data:
    onull o3
install_call:
    addiu r4, r0, 0                    ; entry_offset
    call  #0x009                       ; InstallProgram — sets PC
                                       ; to CODE_VA, replaces mappings,
                                       ; clears GPRs, resets SP. The
                                       ; next instruction fetched is
                                       ; the guest's entry point.

    ; Unreachable: InstallProgram never returns to the loader's PC.
    ; If we somehow get here, fail loudly.
    addiu r4, r0, 98
    call  #0x001
    nop

fail:
    addiu r4, r0, 99
    call  #0x001                       ; TaskExit
    nop
