#!/usr/bin/env python3
"""Generate chunkboot.s — the chunked-boot loader for the MVP "tiny OS".

Sister of gen_linkboot.py (which generates the older single-shot
loader, capped at 256 B). chunkboot.s implements a request/reply
chunk protocol so any-sized program can be booted into a spare CPU.
Together with simorisc's --reset-on-exit and the InstallProgram
primitive (call #0x009), this is what lets the shell run programs:

  - each spare CPU runs chunkboot, gets a guest .orx one chunk at a
    time from linkbootd, CALLs InstallProgram which atomically maps
    the guest at CODE_VA / DATA_VA and jumps to its entry,
  - the guest runs to TaskExit,
  - simorisc resets the CPU and re-runs chunkboot from the top,
  - the loader's fresh announce signals "previous run finished" and
    the slot is back in the pool.

Boot ABI for spare CPUs (set up by oriscrun via --service):

    O5  = linkbootd master    (announce / ack target)
    O6  = (pad — reused by the loader as a scratch slot for the
           R+S self-ref that goes in announce SENDs)
    O7  = oriscterm console   (passed through to guest as O5)
    O8  = oriscterm keyboard  (passed through to guest as O6)
    O9, O10 = pad             (passed through to guest as O7, O8)
    O11 = hostfsd             (passed through to guest as O10)
                              (guest's O9 ends up as null after
                              the loader's pre-jump shift)

Loader-private OR slots (cleared / not seen by guest):

    O12 = chunk source ref    (transient, refreshed per chunk from
                              queue dispatch's O2)
    O13 = writable text obj   (across chunks, dropped after Install)
    O14 = writable data obj   (only used if data_size > 0)
    O15 = full self-svc       (saved at boot from O4; needed every
                              poll because queue dispatch overwrites
                              O1..O4 each iteration)

Wire protocol (with linkbootd):

    Loader → master, announce/ack:
        O1 = linkbootd            (recipient)
        O2 = R+S self-ref         (so master can SEND back)
        R4 = PROCID               (informational)
        R5 = next_offset          (0 on initial announce; otherwise
                                  position + chunk_byte_length of
                                  the chunk just copied)

    Master → loader, chunk:
        O1 = loader's R+S self-ref  (recipient)
        O2 = chunk source ref       (R-only, ≤256 B window)
        R4 = chunk_position        (offset in the concat'd text+data)
        R5 = chunk_byte_length     (≤ CHUNK_BYTES, multiple of 4,
                                   chunks are aligned never to
                                   straddle the text/data boundary)
        R6 = total text size       (constant; loader uses on first
                                   chunk to ObjAlloc the text obj
                                   AND to decide which dst object to
                                   write each chunk into)
        R7 = total data size       (constant; loader uses on first
                                   chunk to ObjAlloc the data obj —
                                   skipped when 0)
"""

from pathlib import Path

CHUNK_BYTES = 256
CHUNK_WORDS = CHUNK_BYTES // 4    # 64 OLW stanzas
HERE = Path(__file__).parent


HEADER = f"""\
; chunkboot.s — chunked-boot loader for spare-CPU program slots.
; GENERATED by gen_chunkboot.py.
;
; A self-contained .orx baked into spare CPUs at launcher startup.
; See examples/linkboot/gen_chunkboot.py for the wire protocol, the
; OR-slot allocation, and how the loader hands off to the guest via
; simorisc's InstallProgram primitive (call #0x009).

.entry main

.set TAG_CODE,    0x4100
.set TAG_DATA,    0x4102
.set CHUNK_BYTES, {CHUNK_BYTES}

.text

main:
    ; Save PROCID (R7) so we can include it in announce/ack SENDs.
    addu  r16, r7, r0

    ; Save the V-cap-bearing self-svc into O15 — every queue poll
    ; overwrites O1..O4 with the sender's OR payload, so we'd lose
    ; the full ref otherwise.
    omov  o15, o4

    ; Derive an R+S self-ref into O6. The boot O6 is a "pad" service
    ; slot that we don't pass through to the guest, so it's free to
    ; hijack. The R+S ref is what the master needs to SEND chunks
    ; back to us.
    omov  o1, o4
    addiu r4, r0, 0x09                 ; R|S
    call  #0x103                       ; ObjDerive
    bne   r2, r0, fail
    nop
    omov  o6, o1                       ; o6 = R+S self-ref

    ; Attach a receive queue to the self-service.
    omov  o1, o15
    addiu r4, r0, 4
    call  #0x203                       ; ReceiveQueueAttach
    bne   r2, r0, fail
    nop

    ; r17 = next_offset across iterations. Starts at 0 (initial
    ; announce). r18 also starts at 0; cleared once we've Object-
    ; Alloc'd the text/data dst objects.
    addu  r17, r0, r0                  ; next_offset
    addu  r18, r0, r0                  ; alloc_done flag (0 = not yet)

; ---------------------------------------------------------------------------
; Request loop. Sends one announce/ack SEND, blocks for one chunk,
; copies it into the dst object, and either continues or finalizes.
; ---------------------------------------------------------------------------

req_loop:
    ; Announce/ack SEND.
    omov  o1, o5                       ; recipient = linkbootd
    omov  o2, o6                       ; R+S self-ref
    onull o3
    onull o4
    addu  r4, r16, r0                  ; PROCID
    addu  r5, r17, r0                  ; next_offset
    addiu r6, r0, 0
    addiu r7, r0, 0
    send  o1

    ; Wait for chunk.
    omov  o1, o15
    addiu r4, r0, -1                   ; infinite
    call  #0x204                       ; ReceiveQueuePoll
    bne   r2, r0, fail
    nop

    ; Queue dispatch: O2 = chunk source; R3 = chunk_position;
    ; R4 = chunk_byte_length; R5 = total_text; R6 = total_data.
    addu  r19, r3, r0                  ; chunk_position
    addu  r20, r4, r0                  ; chunk_byte_length
    addu  r21, r5, r0                  ; total_text_size
    addu  r22, r6, r0                  ; total_data_size
    omov  o12, o2                      ; chunk source ref

    ; First chunk? r18 != 0 means we already allocated.
    bne   r18, r0, copy_chunk
    nop

    ; ObjAlloc text (size = r21).
    addu  r4, r21, r0
    addiu r5, r0, TAG_CODE
    addiu r6, r0, 0x47                 ; R|W|X|C
    addiu r7, r0, 0
    call  #0x100                       ; ObjAlloc
    bne   r2, r0, fail
    nop
    omov  o13, o1                      ; o13 = writable text obj

    ; MapObject text as R|W → text_va in r3.
    omov  o1, o13
    addiu r4, r0, 0
    addiu r5, r0, 0
    addiu r6, r0, 0x03                 ; R|W
    addu  r7, r21, r0
    call  #0x110
    bne   r2, r0, fail
    nop
    addu  r23, r3, r0                  ; r23 = text_va

    ; If data_size > 0, ObjAlloc data + map R|W.
    beq   r22, r0, alloc_done
    nop
    addu  r4, r22, r0
    addiu r5, r0, TAG_DATA
    addiu r6, r0, 0x43                 ; R|W|C  (no X)
    addiu r7, r0, 0
    call  #0x100                       ; ObjAlloc
    bne   r2, r0, fail
    nop
    omov  o14, o1                      ; o14 = writable data obj

    omov  o1, o14
    addiu r4, r0, 0
    addiu r5, r0, 0
    addiu r6, r0, 0x03                 ; R|W
    addu  r7, r22, r0
    call  #0x110
    bne   r2, r0, fail
    nop
    addu  r24, r3, r0                  ; r24 = data_va

alloc_done:
    addiu r18, r0, 1                   ; mark allocations done

copy_chunk:
    ; Decide dst: chunk_position < text_size → text, else data.
    ; r25 = write base; r19 + r20 used to compute next_offset later.
    sltu  r1, r19, r21                 ; r1 = (chunk_position < text_size)
    bne   r1, r0, copy_to_text
    nop
    ; Data chunk: write base = data_va + (chunk_position - text_size)
    subu  r25, r19, r21
    addu  r25, r25, r24
    j     copy_words
    nop
copy_to_text:
    ; Text chunk: write base = text_va + chunk_position
    addu  r25, r23, r19

copy_words:
    ; Words to copy = chunk_byte_length / 4.
    srl   r26, r20, 2

    ; Unrolled OLW + SW with early-exit on r1 == r26. One stanza per
    ; word in the {CHUNK_BYTES}-byte chunk window. Each OLW immediate
    ; is encoded into the instruction so each stanza is hardcoded.
    addu  r1, r0, r0
"""


COPY_STANZA = """\
    olw   r2, {off}(o12)
    sw    r2, {off}(r25)
    addiu r1, r1, 1
    beq   r1, r26, chunk_done
    nop
"""


FOOTER = """\
chunk_done:
    ; next_offset = chunk_position + chunk_byte_length.
    addu  r17, r19, r20

    ; Total = text + data. Last chunk if next_offset == total.
    addu  r1, r21, r22
    beq   r17, r1, finalize
    nop
    j     req_loop
    nop

finalize:
    ; ObjDerive text → R|X|C (drop W).
    omov  o1, o13
    addiu r4, r0, 0x45                 ; R|X|C
    call  #0x103                       ; ObjDerive
    bne   r2, r0, fail
    nop
    omov  o13, o1

    ; If data exists, ObjDerive data → R|C (drop W).
    beq   r22, r0, install
    nop
    omov  o1, o14
    addiu r4, r0, 0x41                 ; R|C
    call  #0x103
    bne   r2, r0, fail
    nop
    omov  o14, o1

install:
    ; Shift the boot service ORs down so the guest sees the standard
    ; ABI (O5 = console, O6 = keyboard, O10 = hostfsd).
    omov  o5, o7
    omov  o6, o8
    onull o7
    onull o8
    onull o9
    omov  o10, o11

    ; CALL InstallProgram. Args: O1 = code ref, O3 = data ref (or
    ; null), R4 = entry offset (always 0 for pcc-built programs).
    omov  o1, o13                      ; guest text ref (R|X|C)
    beq   r22, r0, install_no_data
    nop
    omov  o3, o14                      ; guest data ref (R|C)
    j     install_call
    nop
install_no_data:
    onull o3
install_call:
    addiu r4, r0, 0                    ; entry_offset
    call  #0x009                       ; InstallProgram — sets PC
                                       ; to CODE_VA, replaces mappings,
                                       ; clears GPRs, resets SP. The
                                       ; next instruction fetched is
                                       ; the guest's entry point.

    ; Unreachable: InstallProgram never returns to the loader's PC.
    ; If we somehow get here, fail loudly.
    addiu r4, r0, 98
    call  #0x001
    nop

fail:
    addiu r4, r0, 99
    call  #0x001                       ; TaskExit
    nop
"""


def main() -> None:
    parts = [HEADER]
    for i in range(CHUNK_WORDS):
        parts.append(COPY_STANZA.format(off=i * 4))
    parts.append(FOOTER)
    out = HERE / "chunkboot.s"
    out.write_text("".join(parts))
    print(f"wrote {out} ({out.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
