; linkboot.s — generic link-boot loader.  GENERATED by gen_linkboot.py.
;
; A self-contained .orx that any extra CPU can be booted with. The
; loader announces itself to a "boot master" service at startup, then
; waits for the master to SEND it a code reference; on receipt, it
; copies the code into a fresh local code object, maps it executable,
; and JRs into the loaded module.
;
; The loader's own .orx carries no application code — only the boot
; logic. Useful when you want to spin up extra CPUs whose actual
; programs are decided at runtime (e.g. dynamic worker pools, demand-
; loaded service handlers).
;
; Conventions
; -----------
; Master location: by simorisc convention, when CPU N boots in an
; M-CPU configuration the lowest-PID other CPU's service ref lands
; in O5. The loader announces to whatever ref is in O5.
;
; Announce SEND payload (loader → master):
;     O2 = derived self-service (R+S only — enough for master to SEND)
;     R4 = loader's PROCID
;     R5 = 0  (announcement protocol version)
;
; Boot SEND payload (master → loader, queue-dispatched):
;     O2 = code reference (any byte-typed object with R cap)
;     O3 = optional data reference (becomes the loaded module's O3)
;     R4 = byte length of the module image (must be ≤ 256)
;     R5 = entry offset within the loaded image (0 = start)
;     R6, R7 = reserved (zero)
;
; On entry to the loaded module:
;     PC = mapped_va + R5
;     O3 = data ref (or whatever sender's O3 was; null if none)
;     O4 = self-service ref (preserved from boot)
;     O5 = master service (preserved)
;     O6, O7, O9 = clobbered (loader scratch)
;     other ORs = preserved if untouched at boot

.entry main

.set TAG_CODE,  0x4100
.set MAX_BYTES, 256

.text

; ---------------------------------------------------------------------------
; main — announce, attach queue, poll, copy, derive, map, JR.
; Single straight-line task; no handler dispatch.
; ---------------------------------------------------------------------------
main:
    ; Save PROCID (R7) — primitives clobber R4..R7.
    addu  r16, r7, r0

    ; Derive an R+S self-ref to give the master.
    omov  o1, o4
    addiu r4, r0, 0x09                 ; R|S
    call  #0x103                       ; ObjDerive
    bne   r2, r0, fail
    nop
    omov  o6, o1                       ; o6 = derived ref for master

    ; ReceiveQueueAttach on self-service so we can poll for the boot SEND.
    ; Done BEFORE the first announce so that even an instantaneous master
    ; reply lands in our queue rather than getting dropped.
    omov  o1, o4
    addiu r4, r0, 4                    ; queue depth
    call  #0x203                       ; ReceiveQueueAttach
    bne   r2, r0, fail
    nop

announce_loop:
    ; Announce: SEND to the master in O5.
    omov  o1, o5                       ; recipient
    omov  o2, o6                       ; payload OR slot 1 = derived self-ref
    onull o3
    addu  r4, r16, r0                  ; PROCID
    addiu r5, r0, 0                    ; protocol version
    addiu r6, r0, 0
    addiu r7, r0, 0
    send  o1

    ; Poll for the boot SEND with a finite timeout. If the master isn't
    ; connected to the crossbar yet (a real race in multi-process mode
    ; — both CPUs start asynchronously) the SEND gets dropped silently
    ; by the crossbar; we re-announce on ETIMEOUT until the master shows.
    omov  o1, o4
    lui   r4, 0x0001                   ; ~65 k cycles between retries
    call  #0x204                       ; ReceiveQueuePoll
    beq   r2, r0, got_boot          ; ERR_OK = boot received
    nop
    addiu r1, r0, 7                    ; ERR_ETIMEOUT
    beq   r2, r1, announce_loop     ; re-announce on timeout
    nop
    j     fail                      ; any other error is fatal
    nop

got_boot:
    ; Queue dispatch (Vol VI §6): R3..R6 ← sender R4..R7;
    ; O1..O4 ← sender O1..O4 verbatim.
    ;   O2 = code ref (sender's O2)
    ;   O3 = data ref (sender's O3)
    ;   R3 = length (sender's R4)
    ;   R4 = entry offset (sender's R5)
    addu  r17, r3, r0                  ; r17 = length
    addu  r18, r4, r0                  ; r18 = entry offset
    omov  o6, o2                       ; o6 = code ref
    omov  o7, o3                       ; o7 = data ref (may be null)

    ; Length sanity-check.
    addiu r1, r0, MAX_BYTES
    sltu  r2, r1, r17                  ; r2 = (MAX_BYTES < length)
    bne   r2, r0, fail              ; reject oversize
    nop
    beq   r17, r0, fail             ; reject zero-length
    nop

    ; ObjAlloc a writable local code object.
    addu  r4, r17, r0
    addiu r5, r0, TAG_CODE
    addiu r6, r0, 0x47                 ; R|W|X|C
    addiu r7, r0, 0
    call  #0x100                       ; ObjAlloc → O1 = new ref
    bne   r2, r0, fail
    nop
    omov  o9, o1                       ; o9 = writable local code

    ; MapObject the writable local code as R+W (so we can sw to it).
    omov  o1, o9
    addiu r4, r0, 0
    addiu r5, r0, 0
    addiu r6, r0, 0x03                 ; R|W
    addu  r7, r17, r0
    call  #0x110                       ; → R3 = dst_va
    bne   r2, r0, fail
    nop
    addu  r19, r3, r0                  ; r19 = dst_va

    ; Words-to-copy = length / 4. (length is checked ≤ MAX_BYTES.)
    srl   r20, r17, 2                  ; r20 = num_words

    ; ----- Unrolled copy with early-exit -------------------------------
    ; r1 counts words copied; on each iteration we OLW one word from
    ; the remote source O6 at fixed offset, sw it to dst_va + offset,
    ; and beq-out when r1 == num_words. Each stanza is 5 instructions.
    addu  r1, r0, r0                   ; words copied
    olw   r2, 0(o6)
    sw    r2, 0(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 4(o6)
    sw    r2, 4(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 8(o6)
    sw    r2, 8(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 12(o6)
    sw    r2, 12(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 16(o6)
    sw    r2, 16(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 20(o6)
    sw    r2, 20(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 24(o6)
    sw    r2, 24(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 28(o6)
    sw    r2, 28(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 32(o6)
    sw    r2, 32(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 36(o6)
    sw    r2, 36(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 40(o6)
    sw    r2, 40(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 44(o6)
    sw    r2, 44(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 48(o6)
    sw    r2, 48(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 52(o6)
    sw    r2, 52(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 56(o6)
    sw    r2, 56(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 60(o6)
    sw    r2, 60(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 64(o6)
    sw    r2, 64(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 68(o6)
    sw    r2, 68(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 72(o6)
    sw    r2, 72(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 76(o6)
    sw    r2, 76(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 80(o6)
    sw    r2, 80(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 84(o6)
    sw    r2, 84(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 88(o6)
    sw    r2, 88(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 92(o6)
    sw    r2, 92(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 96(o6)
    sw    r2, 96(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 100(o6)
    sw    r2, 100(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 104(o6)
    sw    r2, 104(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 108(o6)
    sw    r2, 108(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 112(o6)
    sw    r2, 112(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 116(o6)
    sw    r2, 116(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 120(o6)
    sw    r2, 120(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 124(o6)
    sw    r2, 124(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 128(o6)
    sw    r2, 128(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 132(o6)
    sw    r2, 132(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 136(o6)
    sw    r2, 136(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 140(o6)
    sw    r2, 140(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 144(o6)
    sw    r2, 144(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 148(o6)
    sw    r2, 148(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 152(o6)
    sw    r2, 152(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 156(o6)
    sw    r2, 156(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 160(o6)
    sw    r2, 160(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 164(o6)
    sw    r2, 164(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 168(o6)
    sw    r2, 168(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 172(o6)
    sw    r2, 172(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 176(o6)
    sw    r2, 176(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 180(o6)
    sw    r2, 180(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 184(o6)
    sw    r2, 184(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 188(o6)
    sw    r2, 188(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 192(o6)
    sw    r2, 192(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 196(o6)
    sw    r2, 196(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 200(o6)
    sw    r2, 200(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 204(o6)
    sw    r2, 204(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 208(o6)
    sw    r2, 208(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 212(o6)
    sw    r2, 212(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 216(o6)
    sw    r2, 216(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 220(o6)
    sw    r2, 220(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 224(o6)
    sw    r2, 224(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 228(o6)
    sw    r2, 228(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 232(o6)
    sw    r2, 232(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 236(o6)
    sw    r2, 236(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 240(o6)
    sw    r2, 240(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 244(o6)
    sw    r2, 244(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 248(o6)
    sw    r2, 248(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
    olw   r2, 252(o6)
    sw    r2, 252(r19)
    addiu r1, r1, 1
    beq   r1, r20, copy_done
    nop
copy_done:

    ; ObjDerive to drop W; keep R|X|C.
    omov  o1, o9
    addiu r4, r0, 0x45                 ; R|X|C
    call  #0x103                       ; ObjDerive
    bne   r2, r0, fail
    nop
    omov  o9, o1

    ; MapObject as R+X — gives us the executable VA.
    omov  o1, o9
    addiu r4, r0, 0
    addiu r5, r0, 0
    addiu r6, r0, 0x05                 ; R|X
    addu  r7, r17, r0
    call  #0x110                       ; → R3 = exec_va
    bne   r2, r0, fail
    nop
    addu  r3, r3, r18                  ; add entry offset

    ; Final OR setup for the loaded module:
    ;   O1 = loaded code ref (local R|X|C — module can ConsoleWrite from it)
    ;   O3 = data ref the master passed (or null if it didn't pass one).
    ; O1 is already o9 from the last MapObject argument; restore it
    ; explicitly in case future edits reorder things.
    omov  o1, o9
    omov  o3, o7

    ; JR into the module. No return.
    jr    r3
    nop

fail:
    addiu r4, r0, 99
    call  #0x001                       ; TaskExit
    nop
