; @description: Generic link-boot loader. CPU 0 (master) waits for CPU 1's announce SEND, then SENDs back a 40-byte module image (8 instructions of code + an inline "Booted!\n" message). CPU 1 runs the generated linkboot loader: derives a R+S self-ref, attaches a receive queue, announces itself, polls for the boot request, ObjAllocs a writable code object, copies the module bytes from the master via OLW (unrolled with early-exit), derives R|X|C, MapObjects executable, and JRs in. The loaded module ConsoleWrites the message via its own loaded code ref (in O1) and TaskExits.
; @processors: 2
; @expect-stdout: "Booted!\n"
; @expect-exit: 0

; This file is GENERATED by examples/linkboot/gen_linkboot.py. Edit
; that script to change the loader; then re-run it to regenerate.

.entry start

.set TAG_CODE,    0x4100
.set MAX_BYTES,   256
.set MODULE_BYTES, 40

.text

start:
    bne   r7, r0, L_main               ; PROCID != 0 → loader
    nop
    j     M_main                       ; PROCID == 0 → master
    nop

; ---- Master (CPU 0) -------------------------------------------------------
M_main:
    ; Save our data ref before the queue poll overwrites O3.
    omov  o7, o3                       ; o7 = our data segment ref

    ; Attach a queue to our self-service.
    omov  o1, o4
    addiu r4, r0, 4
    call  #0x203                       ; ReceiveQueueAttach
    bne   r2, r0, M_fail
    nop

    ; Poll for the announce.
    omov  o1, o4
    addiu r4, r0, -1                   ; infinite
    call  #0x204                       ; ReceiveQueuePoll
    bne   r2, r0, M_fail
    nop
    ; Now: O2 = loader's R+S self-ref;
    ;      R3 = loader's PROCID (informational).
    omov  o6, o2                       ; o6 = loader's self-ref

    ; Build the boot SEND.
    omov  o1, o6                       ; recipient = loader
    omov  o2, o7                       ; code source = our data segment
    omov  o3, o7                       ; module's data ref = same object
    onull o4
    addiu r4, r0, MODULE_BYTES
    addiu r5, r0, 0
    addiu r6, r0, 0
    addiu r7, r0, 0
    send  o1

    addiu r4, r0, 0
    call  #0x001                       ; TaskExit
    nop

M_fail:
    addiu r4, r0, 1
    call  #0x001
    nop

; ---- Loader (CPU 1+) ------------------------------------------------------
L_main:
    ; Save PROCID (R7) — primitives clobber R4..R7.
    addu  r16, r7, r0

    ; Derive an R+S self-ref to give the master.
    omov  o1, o4
    addiu r4, r0, 0x09                 ; R|S
    call  #0x103                       ; ObjDerive
    bne   r2, r0, L_fail
    nop
    omov  o6, o1                       ; o6 = derived ref for master

    ; ReceiveQueueAttach on self-service so we can poll for the boot SEND.
    ; Done BEFORE the first announce so that even an instantaneous master
    ; reply lands in our queue rather than getting dropped.
    omov  o1, o4
    addiu r4, r0, 4                    ; queue depth
    call  #0x203                       ; ReceiveQueueAttach
    bne   r2, r0, L_fail
    nop

L_announce_loop:
    ; Announce: SEND to the master in O5.
    omov  o1, o5                       ; recipient
    omov  o2, o6                       ; payload OR slot 1 = derived self-ref
    onull o3
    addu  r4, r16, r0                  ; PROCID
    addiu r5, r0, 0                    ; protocol version
    addiu r6, r0, 0
    addiu r7, r0, 0
    send  o1

    ; Poll for the boot SEND with a finite timeout. If the master isn't
    ; connected to the crossbar yet (a real race in multi-process mode
    ; — both CPUs start asynchronously) the SEND gets dropped silently
    ; by the crossbar; we re-announce on ETIMEOUT until the master shows.
    omov  o1, o4
    lui   r4, 0x0001                   ; ~65 k cycles between retries
    call  #0x204                       ; ReceiveQueuePoll
    beq   r2, r0, L_got_boot          ; ERR_OK = boot received
    nop
    addiu r1, r0, 7                    ; ERR_ETIMEOUT
    beq   r2, r1, L_announce_loop     ; re-announce on timeout
    nop
    j     L_fail                      ; any other error is fatal
    nop

L_got_boot:
    ; Queue dispatch (Vol VI §6): R3..R6 ← sender R4..R7;
    ; O1..O4 ← sender O1..O4 verbatim.
    ;   O2 = code ref (sender's O2)
    ;   O3 = data ref (sender's O3)
    ;   R3 = length (sender's R4)
    ;   R4 = entry offset (sender's R5)
    addu  r17, r3, r0                  ; r17 = length
    addu  r18, r4, r0                  ; r18 = entry offset
    omov  o6, o2                       ; o6 = code ref
    omov  o7, o3                       ; o7 = data ref (may be null)

    ; Length sanity-check.
    addiu r1, r0, MAX_BYTES
    sltu  r2, r1, r17                  ; r2 = (MAX_BYTES < length)
    bne   r2, r0, L_fail              ; reject oversize
    nop
    beq   r17, r0, L_fail             ; reject zero-length
    nop

    ; ObjAlloc a writable local code object.
    addu  r4, r17, r0
    addiu r5, r0, TAG_CODE
    addiu r6, r0, 0x47                 ; R|W|X|C
    addiu r7, r0, 0
    call  #0x100                       ; ObjAlloc → O1 = new ref
    bne   r2, r0, L_fail
    nop
    omov  o9, o1                       ; o9 = writable local code

    ; MapObject the writable local code as R+W (so we can sw to it).
    omov  o1, o9
    addiu r4, r0, 0
    addiu r5, r0, 0
    addiu r6, r0, 0x03                 ; R|W
    addu  r7, r17, r0
    call  #0x110                       ; → R3 = dst_va
    bne   r2, r0, L_fail
    nop
    addu  r19, r3, r0                  ; r19 = dst_va

    ; Words-to-copy = length / 4. (length is checked ≤ MAX_BYTES.)
    srl   r20, r17, 2                  ; r20 = num_words

    ; ----- Unrolled copy with early-exit -------------------------------
    ; r1 counts words copied; on each iteration we OLW one word from
    ; the remote source O6 at fixed offset, sw it to dst_va + offset,
    ; and beq-out when r1 == num_words. Each stanza is 5 instructions.
    addu  r1, r0, r0                   ; words copied
    olw   r2, 0(o6)
    sw    r2, 0(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 4(o6)
    sw    r2, 4(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 8(o6)
    sw    r2, 8(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 12(o6)
    sw    r2, 12(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 16(o6)
    sw    r2, 16(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 20(o6)
    sw    r2, 20(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 24(o6)
    sw    r2, 24(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 28(o6)
    sw    r2, 28(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 32(o6)
    sw    r2, 32(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 36(o6)
    sw    r2, 36(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 40(o6)
    sw    r2, 40(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 44(o6)
    sw    r2, 44(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 48(o6)
    sw    r2, 48(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 52(o6)
    sw    r2, 52(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 56(o6)
    sw    r2, 56(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 60(o6)
    sw    r2, 60(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 64(o6)
    sw    r2, 64(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 68(o6)
    sw    r2, 68(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 72(o6)
    sw    r2, 72(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 76(o6)
    sw    r2, 76(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 80(o6)
    sw    r2, 80(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 84(o6)
    sw    r2, 84(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 88(o6)
    sw    r2, 88(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 92(o6)
    sw    r2, 92(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 96(o6)
    sw    r2, 96(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 100(o6)
    sw    r2, 100(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 104(o6)
    sw    r2, 104(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 108(o6)
    sw    r2, 108(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 112(o6)
    sw    r2, 112(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 116(o6)
    sw    r2, 116(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 120(o6)
    sw    r2, 120(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 124(o6)
    sw    r2, 124(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 128(o6)
    sw    r2, 128(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 132(o6)
    sw    r2, 132(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 136(o6)
    sw    r2, 136(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 140(o6)
    sw    r2, 140(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 144(o6)
    sw    r2, 144(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 148(o6)
    sw    r2, 148(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 152(o6)
    sw    r2, 152(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 156(o6)
    sw    r2, 156(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 160(o6)
    sw    r2, 160(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 164(o6)
    sw    r2, 164(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 168(o6)
    sw    r2, 168(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 172(o6)
    sw    r2, 172(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 176(o6)
    sw    r2, 176(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 180(o6)
    sw    r2, 180(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 184(o6)
    sw    r2, 184(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 188(o6)
    sw    r2, 188(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 192(o6)
    sw    r2, 192(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 196(o6)
    sw    r2, 196(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 200(o6)
    sw    r2, 200(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 204(o6)
    sw    r2, 204(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 208(o6)
    sw    r2, 208(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 212(o6)
    sw    r2, 212(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 216(o6)
    sw    r2, 216(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 220(o6)
    sw    r2, 220(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 224(o6)
    sw    r2, 224(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 228(o6)
    sw    r2, 228(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 232(o6)
    sw    r2, 232(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 236(o6)
    sw    r2, 236(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 240(o6)
    sw    r2, 240(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 244(o6)
    sw    r2, 244(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 248(o6)
    sw    r2, 248(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
    olw   r2, 252(o6)
    sw    r2, 252(r19)
    addiu r1, r1, 1
    beq   r1, r20, L_copy_done
    nop
L_copy_done:

    ; ObjDerive to drop W; keep R|X|C.
    omov  o1, o9
    addiu r4, r0, 0x45                 ; R|X|C
    call  #0x103                       ; ObjDerive
    bne   r2, r0, L_fail
    nop
    omov  o9, o1

    ; MapObject as R+X — gives us the executable VA.
    omov  o1, o9
    addiu r4, r0, 0
    addiu r5, r0, 0
    addiu r6, r0, 0x05                 ; R|X
    addu  r7, r17, r0
    call  #0x110                       ; → R3 = exec_va
    bne   r2, r0, L_fail
    nop
    addu  r3, r3, r18                  ; add entry offset

    ; Final OR setup for the loaded module:
    ;   O1 = loaded code ref (local R|X|C — module can ConsoleWrite from it)
    ;   O3 = data ref the master passed (or null if it didn't pass one).
    ; O1 is already o9 from the last MapObject argument; restore it
    ; explicitly in case future edits reorder things.
    omov  o1, o9
    omov  o3, o7

    ; JR into the module. No return.
    jr    r3
    nop

L_fail:
    addiu r4, r0, 99
    call  #0x001                       ; TaskExit
    nop

.data
; Module image — the bytes the loader copies, MapObjects R|X, and JRs to.
; 32 B of code followed by 8 B of inline message; total 40 B = MODULE_BYTES.
; The module reads its message via O1 (= its own loaded code ref, set by
; the loader before JR). Hand-encoded per CONTRACT §5.
;
;   ; O1 is already the loaded code ref on entry; no setup needed.
;   nop
;   addiu r4, r0, 32          ; offset = 32 (past the module's own code)
;   addiu r5, r0, 8           ; count  = 8 ("Booted!\n")
;   call  #0x320              ; ConsoleWrite (reads from O1, locally)
;   addiu r4, r0, 0           ; exit code 0
;   call  #0x001              ; TaskExit
;   nop                       ; CALL has no delay slot, but gives a clean fall-through
;   nop                       ; pad to 32 bytes
    .word 0x00000000                   ; nop
    .word 0x24040020                   ; addiu r4, r0, 32
    .word 0x24050008                   ; addiu r5, r0, 8
    .word 0xF4000320                   ; call  #0x320
    .word 0x24040000                   ; addiu r4, r0, 0
    .word 0xF4000001                   ; call  #0x001
    .word 0x00000000                   ; nop
    .word 0x00000000                   ; nop (pad)

; The message lives at offset 32 of THIS .data segment. The master sends
; MODULE_BYTES (40) so both code and message get copied to the loader.
    .ascii "Booted!\n"
