#!/usr/bin/env python3
"""gen_wm_font.py — generate the WM's 8x16 bitmap font as a C
initializer.

Renders each printable ASCII char (32..126) via ImageMagick's
`magick` command with the given monospace TTF, samples the resulting
PGM bytes, thresholds to 1-bit, and emits one byte per row × 16
rows per char × 95 chars = 1520 bytes total.

Output goes to stdout in the form of a C initializer for a
`static const unsigned char font_8x16[95][16]` array, ready to
paste into ouroboros/oriscwm.c.

Run once with the font of choice; commit the generated bytes
into oriscwm.c.  Re-run only when changing fonts or sizes.

Usage
-----
  python3 tools/gen_wm_font.py
      Render with the default Menlo at 11pt.

  python3 tools/gen_wm_font.py --font PATH [--point-size N] \\
                               [--threshold T]
      Render with a custom font.  PATH must be readable by
      ImageMagick (a .ttf/.ttc/.otf path on disk).  Naming the
      font by family alone usually fails on macOS — give the
      file path.

  python3 tools/gen_wm_font.py --preset lucida
      Shorthand for the Lucida Sans Typewriter shipped inside
      Microsoft Office on macOS.  Used to produce the bitmap
      currently embedded in oriscwm.c — gives the framebuffer
      pane a visually distinct look from oriscterm's Menlo
      console pane, so it's obvious the WM is doing the
      rendering.

Picking a point size
--------------------
Too small and glyphs are unreadable; too large and they don't
fit in the 8×16 cell (descenders + caps want ~12 px of vertical
ink minimum; pointsize 11–12 with most monospace fonts on
macOS clears that without overflowing).
"""

import argparse
import subprocess
import sys
from pathlib import Path

CELL_W     = 8
CELL_H     = 16

CHAR_LO = 32
CHAR_HI = 127       # exclusive

# Named presets.  Each maps to (font_path, point_size).  Add new
# entries here to make `--preset NAME` work; the value should be a
# (path, pointsize) tuple.
PRESETS = {
    "menlo": ("/System/Library/Fonts/Menlo.ttc", 11),
    "courier": ("/System/Library/Fonts/Courier.ttc", 11),
    "lucida": (
        "/Applications/Microsoft Word.app/Contents/Resources/"
        "DFonts/LucidaSansTypewriterRegular.ttf",
        11,
    ),
}

# Filled in by main() from CLI args / preset.
FONT_PATH  = ""
POINT_SIZE = 0
THRESHOLD  = 96     # luminance threshold; any pixel ≥ this is "set"

def render_char(c: int) -> list[int]:
    """Return 16 bytes — one row of 8 bits (MSB = leftmost pixel).
    Spaces and other glyphs that ImageMagick refuses to set in a
    `label:` get a blank cell."""
    char = chr(c)
    if char == " " or char.isspace():
        return [0] * CELL_H
    # ImageMagick chokes on a few characters in `label:` — bare
    # backslash, bare percent, etc.  Use the @-prefix file form for
    # those (writes the char to a temp file, IM reads from it).
    if char in (chr(0x5C), "%", "@"):
        import tempfile, os
        tmp = tempfile.NamedTemporaryFile(mode="w", delete=False, suffix=".txt")
        tmp.write(char)
        tmp.close()
        label_arg = f"label:@{tmp.name}"
        cleanup_path = tmp.name
    else:
        label_arg = f"label:{char}"
        cleanup_path = None
    try:
        proc = subprocess.run(
            [
                "magick",
                "-size", f"{CELL_W}x{CELL_H}",
                "-font", FONT_PATH,
                "-pointsize", str(POINT_SIZE),
                "-background", "black",
                "-fill", "white",
                "-gravity", "center",
                label_arg,
                "-depth", "8",
                "pgm:-",
            ],
            input="",
            check=True,
            capture_output=True,
        )
    finally:
        if cleanup_path:
            import os
            os.unlink(cleanup_path)

    # Parse PGM.  Format: "P5\nW H\nMAX\n<bytes>".  Magick may emit
    # "P5\n# comment\nW H\nMAX\n<bytes>".
    data = proc.stdout
    nl1 = data.index(b'\n');
    line2_start = nl1 + 1
    if data[line2_start:line2_start+1] == b'#':
        # comment line; skip.
        line2_start = data.index(b'\n', line2_start) + 1
    line2_end = data.index(b'\n', line2_start)
    w_h = data[line2_start:line2_end].split()
    w = int(w_h[0]); h = int(w_h[1])
    if w != CELL_W or h != CELL_H:
        raise SystemExit(f"bad PGM size for {char!r}: {w}x{h}")
    line3_end = data.index(b'\n', line2_end + 1)
    pixels = data[line3_end + 1:]
    if len(pixels) != w * h:
        raise SystemExit(f"bad PGM byte count for {char!r}: "
                         f"{len(pixels)} bytes, expected {w*h}")

    rows = []
    for y in range(CELL_H):
        b = 0
        for x in range(CELL_W):
            v = pixels[y * CELL_W + x]
            if v >= THRESHOLD:
                b |= 1 << (7 - x)
        rows.append(b)
    return rows


# Licensing notice baked into every generated face header comment so the
# attribution travels with the assets.  See README "Font licensing" and the
# project NOTICE.  Terms permit commercial use of the real glyphs/fonts; the
# OPEN LOOK trademark has expired (free to use the name).
LICENSE_NOTICE = (
    "OPEN LOOK glyph / Lucida font assets:\n"
    " *   Copyright (c) 1989 Sun Microsystems, Inc.\n"
    " *   Copyright (c) 1985, 1986 Bigelow & Holmes.\n"
    " * Lucida is a registered trademark of Bigelow & Holmes.  Used under the\n"
    " * royalty-free copyright/design-patent license that ships with the\n"
    " * OpenLook CD-ROM; carry these notices in docs + code (see NOTICE)."
)

FONT_MAGIC = 0x574D4631       # 'WMF1' — must match simorisc FONT_MAGIC
FONT_FLAG_PROPORTIONAL = 1


def face_blob(bdf_path, base, count, cell, proportional):
    """Bake a self-describing WM font object and return (blob_bytes, info).

    Layout of the blob (big-endian byte stream, read by the extended
    ObjBlitGlyphs firmware path — see simorisc _blit_glyphs_extended and
    oriscwm.c's wm_font_t):

        word 0  magic 'WMF1'
        word 1  (cell_w << 16) | cell_h
        word 2  (codepoint_base << 16) | n_glyphs
        word 3  (flags << 16) | bytes_per_row
        ...     width_table[n_glyphs]  (u8 advance px each, padded to 4 bytes)
        ...     bitmaps[n_glyphs * bytes_per_row * cell_h]  (u8, MSB-first)

    info carries cell_w/cell_h/bpr/flags/baseline/clipped/present so callers
    can describe the face without re-reading the header.
    """
    from bdf import bake
    cw, ch = (cell if cell else (None, None))
    cells, widths, info = bake(bdf_path, base, count, cw, ch)
    cell_w, cell_h = info["cell_w"], info["cell_h"]
    bpr = (cell_w + 7) // 8
    flags = FONT_FLAG_PROPORTIONAL if proportional else 0

    # Flat big-endian byte stream, padded to 4-byte boundaries so it
    # serialises cleanly as uint32 words.
    blob = bytearray()
    blob += FONT_MAGIC.to_bytes(4, "big")
    blob += ((cell_w << 16) | cell_h).to_bytes(4, "big")
    blob += ((base << 16) | count).to_bytes(4, "big")
    blob += ((flags << 16) | bpr).to_bytes(4, "big")
    blob += bytes(widths)
    while len(blob) % 4:                 # pad width_table to a word boundary
        blob.append(0)
    for rows in cells:
        for row in rows:
            shifted = row << (bpr * 8 - cell_w)
            blob += shifted.to_bytes(bpr, "big")
    while len(blob) % 4:                 # pad bitmaps to a word boundary
        blob.append(0)

    info = dict(info, bpr=bpr, flags=flags)
    return bytes(blob), info


def emit_face(name, bdf_path, base, count, cell, proportional):
    """Emit a self-describing WM font object + its wm_font_t descriptor as
    a C initializer (see face_blob for the binary layout)."""
    blob, info = face_blob(bdf_path, base, count, cell, proportional)
    cell_w, cell_h = info["cell_w"], info["cell_h"]
    flags = info["flags"]
    words = [int.from_bytes(blob[i:i + 4], "big") for i in range(0, len(blob), 4)]

    spacing = "proportional" if proportional else "monospace"
    print(f"/* {name} — {spacing} WM font face.  DO NOT EDIT.")
    print(f" * Generated by tools/gen_wm_font.py --face from")
    print(f" *   {bdf_path}")
    print(f" * Codepoints {base}..{base + count - 1} "
          f"({info['present']} present), cell {cell_w}x{cell_h}, "
          f"baseline row {info['baseline']}.")
    if info["clipped"]:
        clip = ", ".join(str(c) for c in info["clipped"][:12])
        print(f" * Clipped (ink outside cell): {clip}"
              f"{' ...' if len(info['clipped']) > 12 else ''}")
    print(f" *")
    print(f" * {LICENSE_NOTICE}")
    print(f" */")
    print(f"static const unsigned int {name}_blob[] = {{")
    for i in range(0, len(words), 6):
        chunk = ", ".join(f"0x{w:08x}" for w in words[i:i + 6])
        print(f"    {chunk},")
    print(f"}};")
    print(f"static const wm_font_t font_{name} = {{")
    print(f"    {name}_blob, {cell_w}, {cell_h}, {base}, {count}, {flags}")
    print(f"}};")


def main():
    global FONT_PATH, POINT_SIZE, THRESHOLD

    ap = argparse.ArgumentParser(
        description="Generate the WM's 8×16 bitmap font as a C initializer.",
    )
    ap.add_argument("--face",
                    help="Emit a self-describing WM font face named FACE "
                         "(blob + wm_font_t) from --bdf instead of the legacy "
                         "font_8x16 array.  Requires --bdf.")
    ap.add_argument("--bdf",
                    help="Path to an Adobe BDF bitmap font (used with --face).")
    ap.add_argument("--base", type=int, default=32,
                    help="First codepoint of the face (default 32).")
    ap.add_argument("--count", type=int, default=95,
                    help="Number of codepoints to bake (default 95).")
    ap.add_argument("--cell",
                    help="Fixed cell WxH, e.g. 12x16.  Omit to auto-fit the "
                         "cell to the selected glyphs (OPEN LOOK glyph font).")
    ap.add_argument("--proportional", action="store_true",
                    help="Mark the face proportional (advance from width "
                         "table).  Omit for a monospace face.")
    ap.add_argument("--font",
                    help="Path to a TTF/TTC/OTF font file.  Mutually "
                         "exclusive with --preset.")
    ap.add_argument("--point-size", type=int,
                    help="Point size to render at.  Default: 11 (or "
                         "the preset's default).")
    ap.add_argument("--threshold", type=int, default=THRESHOLD,
                    help=f"Luminance threshold 0-255 (default {THRESHOLD}); "
                         "any pixel ≥ this becomes a set bit.")
    ap.add_argument("--preset", choices=sorted(PRESETS),
                    help="Pick a known-good (font, point-size) combo.  "
                         "Mutually exclusive with --font.")
    ap.add_argument("--pcf",
                    help="Path to an X11 PCF bitmap font (e.g. OpenWindows "
                         "lutRS10.pcf).  Emits its glyphs straight into the "
                         f"{CELL_W}x{CELL_H} cell — no ImageMagick, no TTF "
                         "rasterization.  Mutually exclusive with --font/--preset.")
    args = ap.parse_args()

    if args.face:
        if not args.bdf:
            ap.error("--face requires --bdf")
        cell = None
        if args.cell:
            try:
                cw, chh = (int(v) for v in args.cell.lower().split("x"))
            except ValueError:
                ap.error("--cell must look like WxH, e.g. 12x16")
            cell = (cw, chh)
        emit_face(args.face, args.bdf, args.base, args.count, cell,
                  args.proportional)
        return

    if sum(bool(x) for x in (args.font, args.preset, args.pcf)) > 1:
        ap.error("--font, --preset and --pcf are mutually exclusive")

    if args.pcf:
        # Bitmap source: read glyphs straight out of an X11 PCF (no rasterizing).
        from pcf import pcf_cells
        cells, pcf_info = pcf_cells(args.pcf, CELL_W, CELL_H, CHAR_LO, CHAR_HI)
        if not pcf_info["fits"]:
            sys.exit(f"PCF cell is {pcf_info['cell_h']}px tall > {CELL_H}; "
                     f"pick a smaller font: {args.pcf}")
        if pcf_info["clipped"]:
            sys.stderr.write("warning: glyphs clipped to "
                             f"{CELL_W}px wide: {''.join(pcf_info['clipped'])}\n")
        get_rows = lambda c: cells[c]
        src_desc = (f"{args.pcf}\n * X11 PCF bitmap — ascent {pcf_info['ascent']}, "
                    f"descent {pcf_info['descent']}, baseline row {pcf_info['baseline']}")
    else:
        # Vector source: rasterize a TTF/TTC/OTF via ImageMagick.
        if args.preset:
            FONT_PATH, POINT_SIZE = PRESETS[args.preset]
        elif args.font:
            FONT_PATH, POINT_SIZE = args.font, 11
        else:
            FONT_PATH, POINT_SIZE = PRESETS["menlo"]
        if args.point_size is not None:
            POINT_SIZE = args.point_size
        THRESHOLD = args.threshold
        if not Path(FONT_PATH).exists():
            sys.exit(f"font not found: {FONT_PATH}")
        get_rows = render_char
        src_desc = (f"{FONT_PATH}\n * Point size {POINT_SIZE}, threshold "
                    f"{THRESHOLD} (ImageMagick rasterized)")

    print(f"/* Generated by tools/gen_wm_font.py — DO NOT EDIT.")
    print(f" * Source: {src_desc}")
    print(f" * Cell {CELL_W}×{CELL_H}.")
    print(f" * 95 printable ASCII chars (codepoints {CHAR_LO}..{CHAR_HI - 1}),")
    print(f" * 16 pixel rows per char packed into 4 big-endian 32-bit")
    print(f" * words.  Each word holds 4 consecutive rows, MSB = earlier")
    print(f" * row.  Within a row, MSB = leftmost pixel.")
    print(f" *")
    print(f" * Why uint32 not uint8?  pcc-orisc serializes char[] inits")
    print(f" * via .ascii with C-style octal escapes; for some byte")
    print(f" * sequences it emits malformed escapes (e.g. \\\\08 or \\\\208)")
    print(f" * that the GAS-compatible assembler parses as a shorter octal")
    print(f" * followed by a literal digit, dropping bytes from the")
    print(f" * assembled .data section.  .word emission has no such")
    print(f" * ambiguity.")
    print(f" */")
    print(f"static const unsigned int font_8x16"
          f"[{CHAR_HI - CHAR_LO}][{CELL_H // 4}] = {{")
    for c in range(CHAR_LO, CHAR_HI):
        rows = get_rows(c)
        # Pack 16 bytes into 4 big-endian uint32_t words.
        words = []
        for w in range(CELL_H // 4):
            base = w * 4
            v = ((rows[base]     << 24) |
                 (rows[base + 1] << 16) |
                 (rows[base + 2] << 8)  |
                  rows[base + 3])
            words.append(v)
        hex_words = ", ".join(f"0x{w:08x}" for w in words)
        comment = repr(chr(c)) if 32 < c < 127 else f"\\x{c:02x}"
        print(f"    /* {comment:>5} */ {{ {hex_words} }},")
    print(f"}};")


if __name__ == "__main__":
    main()
