#!/usr/bin/env python3
"""gen_wm_font.py — generate the WM's 8x16 bitmap font as a C
initializer.

Renders each printable ASCII char (32..126) via ImageMagick's
`magick` command with the given monospace TTF, samples the resulting
PGM bytes, thresholds to 1-bit, and emits one byte per row × 16
rows per char × 95 chars = 1520 bytes total.

Output goes to stdout in the form of a C initializer for a
`static const unsigned char font_8x16[95][16]` array, ready to
paste into ouroboros/oriscwm.c.

Run once with the font of choice; commit the generated bytes
into oriscwm.c.  Re-run only when changing fonts or sizes.

Usage
-----
  python3 tools/gen_wm_font.py
      Render with the default Menlo at 11pt.

  python3 tools/gen_wm_font.py --font PATH [--point-size N] \\
                               [--threshold T]
      Render with a custom font.  PATH must be readable by
      ImageMagick (a .ttf/.ttc/.otf path on disk).  Naming the
      font by family alone usually fails on macOS — give the
      file path.

  python3 tools/gen_wm_font.py --preset lucida
      Shorthand for the Lucida Sans Typewriter shipped inside
      Microsoft Office on macOS.  Used to produce the bitmap
      currently embedded in oriscwm.c — gives the framebuffer
      pane a visually distinct look from oriscterm's Menlo
      console pane, so it's obvious the WM is doing the
      rendering.

Picking a point size
--------------------
Too small and glyphs are unreadable; too large and they don't
fit in the 8×16 cell (descenders + caps want ~12 px of vertical
ink minimum; pointsize 11–12 with most monospace fonts on
macOS clears that without overflowing).
"""

import argparse
import subprocess
import sys
from pathlib import Path

CELL_W     = 8
CELL_H     = 16

CHAR_LO = 32
CHAR_HI = 127       # exclusive

# Named presets.  Each maps to (font_path, point_size).  Add new
# entries here to make `--preset NAME` work; the value should be a
# (path, pointsize) tuple.
PRESETS = {
    "menlo": ("/System/Library/Fonts/Menlo.ttc", 11),
    "courier": ("/System/Library/Fonts/Courier.ttc", 11),
    "lucida": (
        "/Applications/Microsoft Word.app/Contents/Resources/"
        "DFonts/LucidaSansTypewriterRegular.ttf",
        11,
    ),
}

# Filled in by main() from CLI args / preset.
FONT_PATH  = ""
POINT_SIZE = 0
THRESHOLD  = 96     # luminance threshold; any pixel ≥ this is "set"

def render_char(c: int) -> list[int]:
    """Return 16 bytes — one row of 8 bits (MSB = leftmost pixel).
    Spaces and other glyphs that ImageMagick refuses to set in a
    `label:` get a blank cell."""
    char = chr(c)
    if char == " " or char.isspace():
        return [0] * CELL_H
    # ImageMagick chokes on a few characters in `label:` — bare
    # backslash, bare percent, etc.  Use the @-prefix file form for
    # those (writes the char to a temp file, IM reads from it).
    if char in (chr(0x5C), "%", "@"):
        import tempfile, os
        tmp = tempfile.NamedTemporaryFile(mode="w", delete=False, suffix=".txt")
        tmp.write(char)
        tmp.close()
        label_arg = f"label:@{tmp.name}"
        cleanup_path = tmp.name
    else:
        label_arg = f"label:{char}"
        cleanup_path = None
    try:
        proc = subprocess.run(
            [
                "magick",
                "-size", f"{CELL_W}x{CELL_H}",
                "-font", FONT_PATH,
                "-pointsize", str(POINT_SIZE),
                "-background", "black",
                "-fill", "white",
                "-gravity", "center",
                label_arg,
                "-depth", "8",
                "pgm:-",
            ],
            input="",
            check=True,
            capture_output=True,
        )
    finally:
        if cleanup_path:
            import os
            os.unlink(cleanup_path)

    # Parse PGM.  Format: "P5\nW H\nMAX\n<bytes>".  Magick may emit
    # "P5\n# comment\nW H\nMAX\n<bytes>".
    data = proc.stdout
    nl1 = data.index(b'\n');
    line2_start = nl1 + 1
    if data[line2_start:line2_start+1] == b'#':
        # comment line; skip.
        line2_start = data.index(b'\n', line2_start) + 1
    line2_end = data.index(b'\n', line2_start)
    w_h = data[line2_start:line2_end].split()
    w = int(w_h[0]); h = int(w_h[1])
    if w != CELL_W or h != CELL_H:
        raise SystemExit(f"bad PGM size for {char!r}: {w}x{h}")
    line3_end = data.index(b'\n', line2_end + 1)
    pixels = data[line3_end + 1:]
    if len(pixels) != w * h:
        raise SystemExit(f"bad PGM byte count for {char!r}: "
                         f"{len(pixels)} bytes, expected {w*h}")

    rows = []
    for y in range(CELL_H):
        b = 0
        for x in range(CELL_W):
            v = pixels[y * CELL_W + x]
            if v >= THRESHOLD:
                b |= 1 << (7 - x)
        rows.append(b)
    return rows


def main():
    global FONT_PATH, POINT_SIZE, THRESHOLD

    ap = argparse.ArgumentParser(
        description="Generate the WM's 8×16 bitmap font as a C initializer.",
    )
    ap.add_argument("--font",
                    help="Path to a TTF/TTC/OTF font file.  Mutually "
                         "exclusive with --preset.")
    ap.add_argument("--point-size", type=int,
                    help="Point size to render at.  Default: 11 (or "
                         "the preset's default).")
    ap.add_argument("--threshold", type=int, default=THRESHOLD,
                    help=f"Luminance threshold 0-255 (default {THRESHOLD}); "
                         "any pixel ≥ this becomes a set bit.")
    ap.add_argument("--preset", choices=sorted(PRESETS),
                    help="Pick a known-good (font, point-size) combo.  "
                         "Mutually exclusive with --font.")
    args = ap.parse_args()

    if args.font and args.preset:
        ap.error("--font and --preset are mutually exclusive")

    # Establish (font, default point-size) from preset / --font / fallback.
    if args.preset:
        FONT_PATH, POINT_SIZE = PRESETS[args.preset]
    elif args.font:
        FONT_PATH, POINT_SIZE = args.font, 11
    else:
        FONT_PATH, POINT_SIZE = PRESETS["menlo"]

    # Explicit --point-size wins over preset defaults.
    if args.point_size is not None:
        POINT_SIZE = args.point_size
    THRESHOLD = args.threshold

    if not Path(FONT_PATH).exists():
        sys.exit(f"font not found: {FONT_PATH}")

    print(f"/* Generated by tools/gen_wm_font.py — DO NOT EDIT.")
    print(f" * Source font: {FONT_PATH}")
    print(f" * Point size: {POINT_SIZE}, cell {CELL_W}×{CELL_H}, "
          f"threshold {THRESHOLD}.")
    print(f" * 95 printable ASCII chars (codepoints {CHAR_LO}..{CHAR_HI - 1}),")
    print(f" * 16 pixel rows per char packed into 4 big-endian 32-bit")
    print(f" * words.  Each word holds 4 consecutive rows, MSB = earlier")
    print(f" * row.  Within a row, MSB = leftmost pixel.")
    print(f" *")
    print(f" * Why uint32 not uint8?  pcc-orisc serializes char[] inits")
    print(f" * via .ascii with C-style octal escapes; for some byte")
    print(f" * sequences it emits malformed escapes (e.g. \\\\08 or \\\\208)")
    print(f" * that the GAS-compatible assembler parses as a shorter octal")
    print(f" * followed by a literal digit, dropping bytes from the")
    print(f" * assembled .data section.  .word emission has no such")
    print(f" * ambiguity.")
    print(f" */")
    print(f"static const unsigned int font_8x16"
          f"[{CHAR_HI - CHAR_LO}][{CELL_H // 4}] = {{")
    for c in range(CHAR_LO, CHAR_HI):
        rows = render_char(c)
        # Pack 16 bytes into 4 big-endian uint32_t words.
        words = []
        for w in range(CELL_H // 4):
            base = w * 4
            v = ((rows[base]     << 24) |
                 (rows[base + 1] << 16) |
                 (rows[base + 2] << 8)  |
                  rows[base + 3])
            words.append(v)
        hex_words = ", ".join(f"0x{w:08x}" for w in words)
        comment = repr(chr(c)) if 32 < c < 127 else f"\\x{c:02x}"
        print(f"    /* {comment:>5} */ {{ {hex_words} }},")
    print(f"}};")


if __name__ == "__main__":
    main()
