#!/usr/bin/env python3
"""gen_wm_font.py — generate the WM's 8x16 bitmap font as a C
initializer.

Renders each printable ASCII char (32..126) via ImageMagick's
`convert` command with a known monospace TTF, samples the resulting
PGM bytes, thresholds to 1-bit, and emits one byte per row × 16
rows per char × 95 chars = 1520 bytes total.

Output goes to stdout in the form of a C initializer for a
`static const unsigned char font_8x16[95][16]` array, ready to
paste into ouroboros/oriscwm.c.

Run once; commit the generated bytes.  Re-run only if we want to
change fonts or sizes.
"""

import subprocess
import sys
from pathlib import Path

# Tweakables.  The point size is the most influential — too small
# and glyphs are unreadable; too large and they don't fit in the
# 8×16 cell.  10..12 with Menlo gives good results on macOS.
FONT_PATH  = "/System/Library/Fonts/Menlo.ttc"
POINT_SIZE = 11
CELL_W     = 8
CELL_H     = 16
THRESHOLD  = 96     # luminance threshold; any pixel ≥ this is "set"

CHAR_LO = 32
CHAR_HI = 127       # exclusive

def render_char(c: int) -> list[int]:
    """Return 16 bytes — one row of 8 bits (MSB = leftmost pixel).
    Spaces and other glyphs that ImageMagick refuses to set in a
    `label:` get a blank cell."""
    char = chr(c)
    if char == " " or char.isspace():
        return [0] * CELL_H
    # ImageMagick chokes on a few characters in `label:` — bare
    # backslash, bare percent, etc.  Use the @-prefix file form for
    # those (writes the char to a temp file, IM reads from it).
    if char in (chr(0x5C), "%", "@"):
        import tempfile, os
        tmp = tempfile.NamedTemporaryFile(mode="w", delete=False, suffix=".txt")
        tmp.write(char)
        tmp.close()
        label_arg = f"label:@{tmp.name}"
        cleanup_path = tmp.name
    else:
        label_arg = f"label:{char}"
        cleanup_path = None
    try:
        proc = subprocess.run(
            [
                "magick",
                "-size", f"{CELL_W}x{CELL_H}",
                "-font", FONT_PATH,
                "-pointsize", str(POINT_SIZE),
                "-background", "black",
                "-fill", "white",
                "-gravity", "center",
                label_arg,
                "-depth", "8",
                "pgm:-",
            ],
            input="",
            check=True,
            capture_output=True,
        )
    finally:
        if cleanup_path:
            import os
            os.unlink(cleanup_path)

    # Parse PGM.  Format: "P5\nW H\nMAX\n<bytes>".  Magick may emit
    # "P5\n# comment\nW H\nMAX\n<bytes>".
    data = proc.stdout
    nl1 = data.index(b'\n');
    line2_start = nl1 + 1
    if data[line2_start:line2_start+1] == b'#':
        # comment line; skip.
        line2_start = data.index(b'\n', line2_start) + 1
    line2_end = data.index(b'\n', line2_start)
    w_h = data[line2_start:line2_end].split()
    w = int(w_h[0]); h = int(w_h[1])
    if w != CELL_W or h != CELL_H:
        raise SystemExit(f"bad PGM size for {char!r}: {w}x{h}")
    line3_end = data.index(b'\n', line2_end + 1)
    pixels = data[line3_end + 1:]
    if len(pixels) != w * h:
        raise SystemExit(f"bad PGM byte count for {char!r}: "
                         f"{len(pixels)} bytes, expected {w*h}")

    rows = []
    for y in range(CELL_H):
        b = 0
        for x in range(CELL_W):
            v = pixels[y * CELL_W + x]
            if v >= THRESHOLD:
                b |= 1 << (7 - x)
        rows.append(b)
    return rows


def main():
    if not Path(FONT_PATH).exists():
        sys.exit(f"font not found: {FONT_PATH}")

    print(f"/* Generated by tools/gen_wm_font.py — DO NOT EDIT.")
    print(f" * Source font: {FONT_PATH}")
    print(f" * Point size: {POINT_SIZE}, cell {CELL_W}×{CELL_H}, "
          f"threshold {THRESHOLD}.")
    print(f" * 95 printable ASCII chars (codepoints {CHAR_LO}..{CHAR_HI - 1}),")
    print(f" * 16 bytes per char (one row per byte, MSB = leftmost pixel).")
    print(f" */")
    print(f"static const unsigned char font_8x16"
          f"[{CHAR_HI - CHAR_LO}][{CELL_H}] = {{")
    for c in range(CHAR_LO, CHAR_HI):
        rows = render_char(c)
        hex_bytes = ", ".join(f"0x{b:02x}" for b in rows)
        comment = repr(chr(c)) if 32 < c < 127 else f"\\x{c:02x}"
        print(f"    /* {comment:>5} */ {{ {hex_bytes} }},")
    print(f"}};")


if __name__ == "__main__":
    main()
